tags_list = [["soldier", "citizen", "none"],
        ["child", "teenager", "adult", "none"],
        ["female", "male", "none"],
        ["recent event", "old event", "none"],
        ["long period", "short period", "none"],
        ["sexual assault", "none"],
        ["suicide", "none"],
        ["family support", "orphan", "none"],
        ["therapy history", "new to therapy", "none"],
        ["chronic disease", "healthy", "none"],
        ["difficult childhood", "none"],
        ["physical violence", "none"],
        ["dissociation", "none"],
        ["sleep disorder", "eating disorder", "none"],
        ["delusions", "flashbacks", "none"],
        ["lack of judgement", "none"],
        ["drugs addiction", "alcohol addiction", "none"],
        ["drugs usage", "none"],
        ["religious", "none"]
]
